import type { GlobalLocale } from "./locale-preference";

export const editorCopy = {
  en: {
    loginFailed: "Login failed", loadFailed: "Unable to load article", saveFailed: "Save failed", publishFailed: "Publishing failed", forkFailed: "Fork failed", deleteFailed: "Deletion failed", unsavedChanges: "You have unsaved changes. Leave this page and discard them?",
    savedAdmin: "Draft saved. You can approve and publish it from the editor.", submitted: "Submitted for administrator review.", publishedNotified: "Published and the author has been notified", publishedMailFailed: "Published, but the notification email failed.", deletedNotified: "Deleted and the author has been notified.", deletedMailFailed: "Deleted, but the notification email failed.", deletedNoEmail: "Deleted; the author has no email address to notify.",
    noSlug: "No slug", untitled: "Untitled", moreActions: "More actions", editor: "Markdown Editor", loginDescription: "Every verified account can submit article changes. An administrator must approve publication.", identifier: "Name or email", password: "Password", login: "Log in", articles: "Articles", refresh: "Refresh", create: "New", drafts: "Drafts", publishedPosts: "Published", noDrafts: "No drafts", missing: "Missing", noPublished: "No published posts", edit: "Edit", details: "Show details", approvePublish: "Approve and publish", delete: "Delete", logout: "Log out",
    editorDescription: "Changes are saved as pending. Only administrators can approve publication.", published: "Published", properties: "Edit properties", saveDraft: "Save draft", submitReview: "Submit for review", language: "Language", slugHelp: "Lowercase letters, numbers, and hyphens", title: "Title", description: "Description", tags: "Tags", tagsHelp: "Separate with commas; maximum 20", done: "Done",
    postDetails: "Post details", status: "Status", pendingDraft: "Pending draft", lastUpdated: "Last updated", author: "Author", owner: "Owner", lastEditor: "Last editor", source: "Source", newArticle: "New article", noRecord: "Not recorded", noTags: "No tags", contributors: "Contributors", noContributions: "No published contributions yet", contributions: "contributions", close: "Close", approvalNotice: "The submitter will be notified by email after publication. You can describe changes made during approval.", messageAuthor: "Message to the author (optional)", cancel: "Cancel", confirmApprove: "Approve and notify", deletePending: "Delete pending draft", deletePublished: "Delete published post", deleteNotice: "This will delete “{title}”. The reason will be emailed to the author; published posts cannot be restored from the editor.", deleteReason: "Deletion reason", confirmDelete: "Delete and notify", preview: "Preview", refreshPreview: "Refresh preview",
  },
  zh: {
    loginFailed: "登录失败", loadFailed: "无法加载文章", saveFailed: "保存失败", publishFailed: "发布失败", forkFailed: "Fork 失败", deleteFailed: "删除失败", unsavedChanges: "你有尚未保存的修改，确定离开并放弃这些修改吗？", savedAdmin: "草稿已保存，可直接在编辑器中批准发布", submitted: "已提交，等待管理员审核", publishedNotified: "已发布并通知作者", publishedMailFailed: "已发布，但邮件通知失败", deletedNotified: "已删除并通知作者", deletedMailFailed: "已删除，但邮件通知失败", deletedNoEmail: "已删除；该文章没有可通知的作者邮箱",
    noSlug: "未设置 slug", untitled: "未命名", moreActions: "更多操作", editor: "Markdown 编辑器", loginDescription: "所有已验证账号都可以提交文章修改；发布需要管理员批准。", identifier: "昵称或邮箱", password: "密码", login: "登录", articles: "文章", refresh: "刷新", create: "新建", drafts: "草稿", publishedPosts: "现有文章", noDrafts: "暂无草稿", missing: "缺少", noPublished: "暂无现有文章", edit: "打开编辑", details: "显示详细信息", approvePublish: "批准并发布", delete: "删除", logout: "退出登录",
    editorDescription: "修改会保存到 pending；只有管理员可以批准发布。", published: "已发布", properties: "修改文档属性", saveDraft: "保存草稿", submitReview: "提交待审核", language: "语言", slugHelp: "小写字母、数字和连字符", title: "标题", description: "摘要", tags: "标签", tagsHelp: "用英文逗号分隔，最多 20 个", done: "完成",
    postDetails: "文章详细信息", status: "状态", pendingDraft: "待审核草稿", lastUpdated: "最后更新", author: "作者", owner: "所有者", lastEditor: "最后编辑者", source: "来源", newArticle: "新文章", noRecord: "未记录", noTags: "无标签", contributors: "贡献者", noContributions: "暂无已发布贡献记录", contributions: "次贡献", close: "关闭", approvalNotice: "发布后会邮件通知提交者。你可以说明审批时改动了哪些内容。", messageAuthor: "给作者的留言（可选）", cancel: "取消", confirmApprove: "确认批准并通知", deletePending: "删除待审核草稿", deletePublished: "删除正式文章", deleteNotice: "将删除“{title}”。删除理由会通过邮件发送给作者；正式文章删除后无法在编辑器中恢复。", deleteReason: "删除理由", confirmDelete: "确认删除并通知", preview: "预览", refreshPreview: "更新预览",
  },
} satisfies Record<GlobalLocale, Record<string, string>>;
