import type { Locale } from "@lib/i18n/app";

const en = {
  title: "Vocabulary Practice", subtitle: "Practice vocabulary from selectable learning databases.", dataset: "Vocabulary database", phonetic: "Sound → word", meaning: "Meaning → word", word: "Word → meaning", autoSpeak: "Read each new word automatically", listen: "Listen again", answerWord: "Type the English word", answerRest: "Type the remaining letters", answerMeaning: "Meaning", check: "Check", checking: "Checking…", next: "Next question", reveal: "Show answer", reset: "Regenerate", progress: "Progress", correct: "Correct", wrong: "Incorrect", answer: "Answer", ambiguous: "This definition matches multiple entries", loadFailed: "Unable to load questions.", gradeFailed: "The AI did not complete the meaning check.", llmNeeded: "Configure an LLM provider and model in Settings to grade meanings.", settings: "Open Settings", model: "Model", source: "NCEE headwords: gaokao-vocab · definitions and examples: built-in dictionary", favorite: "Add to collection", chooseCollection: "Choose a collection", newCollection: "+ New…", collectionName: "Collection name", saved: "Saved to collection", cloudSaved: "Progress uploaded", sync: "Sync", syncTitle: "Manual progress sync", uploadProgress: "Upload local progress", downloadProgress: "Download cloud progress", syncHint: "Only the current database and practice mode are affected. Download replaces local progress.", noCloudProgress: "No cloud progress exists for this database and mode.", syncFailed: "Unable to sync progress.",
  firstLetterHintDescription: "Always reveal the first letter as one of the hints.", firstLetterHint: "First-letter hint", pauseAfterCorrectDescription: "Stay on the current question after a correct answer to review it.", pauseAfterCorrect: "Pause after correct", autoSpeakDescription: "Automatically pronounce the word when each new question appears.", autoSpeakLabel: "Automatically speak new questions", answerSavedToDefault: "Answer shown and saved to default", answerSaveFailed: "Answer shown, but it could not be saved", removedFromCollection: "Removed from collection", removeFailed: "Unable to remove word", collectionDeleted: "Collection deleted", collectionDeleteFailed: "Unable to delete the collection", restoredToOriginal: "Restored to the original collection", movedToTransferred: "Moved to transferred", transferFailed: "Unable to move; the destination may already contain this word, or the original collection no longer exists", cloudProgressDownloaded: "Cloud progress downloaded", addCustomWord: "Add custom word", createCollection: "New collection", deleteCurrentCollection: "Delete current collection", bucket: "Bucket", refillThreshold: "Refill threshold", tokens: "Tokens", previousWithShortcut: "Previous (Ctrl + F)", previous: "Previous", findWord: "Find an English word", searchWithShortcut: "Search (Enter)", nextWithShortcut: "Next (Ctrl + J)", lookUpCurrentWord: "Look up the current word in Dictionary", openDictionary: "Open dictionary", restoreToOriginalCollection: "Restore to original collection", moveToTransferred: "Move to transferred", removeFromCollectionWithShortcut: "Remove from collection (Ctrl + D)", showPronunciationWithShortcut: "Show pronunciation and speak (Ctrl + P)", showPronunciation: "Show pronunciation and speak", dictionaryExamples: "Dictionary examples", forgotWithShortcut: "Forgot (;)", forgot: "Forgot", customWordSaved: "Custom word saved", dictionary: "Dictionary", closeDictionary: "Close dictionary", searchTitle: (word: string) => `Search: ${word}`, noMatchingWords: "No matching words found", close: "Close", cancel: "Cancel", deleteCollection: "Delete collection", deleteCollectionConfirmation: (name: string) => `Delete “${name}”? All its words and practice progress will be permanently deleted.`, delete: "Delete",
};

const zh: typeof en = {
  title: "词汇练习", subtitle: "从可切换的学习词库中练习英语词汇。", dataset: "词汇数据库", phonetic: "根据音标写单词", meaning: "根据意思写单词", word: "根据单词写意思", autoSpeak: "新题自动朗读", listen: "再次朗读", answerWord: "输入英文单词", answerRest: "填写剩余字母", answerMeaning: "填写这个义项", check: "检查答案", checking: "正在批改…", next: "下一题", reveal: "查看答案", reset: "重新生成", progress: "当前进度", correct: "正确", wrong: "回答错误", answer: "参考答案", ambiguous: "该释义对应多个词条", loadFailed: "无法批量载入题目。", gradeFailed: "AI 未完成本次词义批改。", llmNeeded: "请先在设置中配置 LLM Provider 和 Model，才能批改中文释义。", settings: "打开设置", model: "模型", source: "NCEE 词目：gaokao-vocab · 释义与例句：内置词典", favorite: "收藏到词汇表", chooseCollection: "选择收藏夹", newCollection: "+ 新建…", collectionName: "收藏夹名称", saved: "已收藏（云端保存）", cloudSaved: "本地进度已上传", sync: "同步", syncTitle: "手动同步进度", uploadProgress: "上传本地进度", downloadProgress: "下载云端进度", syncHint: "仅同步当前词库和练习模式；下载会覆盖本地进度。", noCloudProgress: "云端没有当前词库和模式的进度。", syncFailed: "进度同步失败。",
  firstLetterHintDescription: "开启后，每题至少显示首字母作为固定提示。", firstLetterHint: "首字母提示", pauseAfterCorrectDescription: "开启后，答对不会自动进入下一题，便于查看答案和例句。", pauseAfterCorrect: "答对后停留", autoSpeakDescription: "开启后，每道新题都会自动朗读当前单词。", autoSpeakLabel: "新题自动朗读", answerSavedToDefault: "答案已显示，并已收藏到 default", answerSaveFailed: "答案已显示，但收藏失败", removedFromCollection: "已从收藏夹删除", removeFailed: "删除失败", collectionDeleted: "收藏夹已删除", collectionDeleteFailed: "无法删除收藏夹", restoredToOriginal: "已恢复到原收藏夹", movedToTransferred: "已转移到 transferred", transferFailed: "转移失败；目标中可能已有这个词，或原收藏夹已不存在", cloudProgressDownloaded: "云端进度已下载", addCustomWord: "新增自定义词汇", createCollection: "新建收藏夹", deleteCurrentCollection: "删除当前收藏夹", bucket: "桶剩余", refillThreshold: "补充阈值", tokens: "令牌", previousWithShortcut: "后退（Ctrl + F）", previous: "后退", findWord: "查找英文单词", searchWithShortcut: "查找（Enter）", nextWithShortcut: "前进（Ctrl + J）", lookUpCurrentWord: "在词典中查看当前单词", openDictionary: "打开词典", restoreToOriginalCollection: "恢复到原收藏夹", moveToTransferred: "转移到 transferred", removeFromCollectionWithShortcut: "从收藏夹删除（Ctrl + D）", showPronunciationWithShortcut: "显示音标并朗读（Ctrl + P）", showPronunciation: "显示音标并朗读", dictionaryExamples: "词典例句", forgotWithShortcut: "忘记了（;）", forgot: "忘记了", customWordSaved: "自定义词汇已保存", dictionary: "词典", closeDictionary: "关闭词典", searchTitle: (word: string) => `查找单词：${word}`, noMatchingWords: "没有找到匹配的单词", close: "关闭", cancel: "取消", deleteCollection: "删除收藏夹", deleteCollectionConfirmation: (name: string) => `确定删除“${name}”吗？其中的所有词条和练习进度都会被删除，此操作无法撤销。`, delete: "删除",
};

export const nceeVocabularyTranslations: Record<Locale, typeof en> = { en, zh };
