"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, CircularProgress, Divider, IconButton, Stack, TextField, Tooltip, Typography } from "@mui/material";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import ChevronLeftRoundedIcon from "@mui/icons-material/ChevronLeftRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import MenuBookRoundedIcon from "@mui/icons-material/MenuBookRounded";
import StorageRoundedIcon from "@mui/icons-material/StorageRounded";
import CollectionReviewDetails, { reviewDate } from "@components/vocabulary/CollectionReviewDetails";
import VocabularyUsageDialog from "@components/vocabulary/VocabularyUsageDialog";
import Footer from "@components/ui/layout/Footer";
import { toast } from "@components/ui/feedback/toast";
import { useDocumentTitle } from "@hooks/app/useDocumentTitle";
import { useAuth } from "@lib/client-api/use-auth";
import { vocabularyDrillApi, vocabularyPracticeApi, type VocabularyCollection, type VocabularyUsage } from "@lib/client-api";
import { useI18n } from "@lib/i18n/app";

const words = {
  en: { title: "User Data", description: "Manage data stored for your account.", vocabulary: "Vocabulary learning", vocabularyHint: "Collections shared by vocabulary and sentence practice", add: "Add sentence usage", empty: "This collection is empty.", drillWords: "Vocabulary practice", sentenceUsages: "Sentence practice", correct: "Correct", wrong: "Wrong", recent: "Recent 8", never: "Not practiced", history: "Last 5 attempts", example: "Example", feedback: "Feedback", corrected: "Correction", delete: "Delete usage", loadFailed: "Unable to load user data.", saveFailed: "Unable to save user data.", saved: "Sentence-practice usage added", removed: "Item removed", sentencePractice: "Sentence practice", vocabularyPractice: "Vocabulary practice", login: "Sign in to manage User Data.", verify: "Verify your email before managing User Data.", signIn: "Sign in" },
  zh: { title: "用户数据", description: "管理保存在账户中的个人数据。", vocabulary: "词汇学习", vocabularyHint: "词汇练习和造句练习共用收藏夹", add: "添加造句词义", empty: "这个收藏夹还是空的。", drillWords: "词汇练习", sentenceUsages: "造句练习", correct: "正确", wrong: "错误", recent: "最近 8 次", never: "尚未练习", history: "最近 5 次记录", example: "例句", feedback: "反馈", corrected: "修改建议", delete: "删除用法", loadFailed: "无法加载用户数据。", saveFailed: "无法保存用户数据。", saved: "已添加造句练习词义", removed: "已删除条目", sentencePractice: "造句练习", vocabularyPractice: "词汇练习", login: "登录后才能管理用户数据。", verify: "请先验证邮箱再管理用户数据。", signIn: "去登录" },
};

export default function UserDataClient() {
  const { locale } = useI18n(); const copy = words[locale]; const { status, isAuthenticated, user } = useAuth(); useDocumentTitle(copy.title);
  const [usages, setUsages] = useState<VocabularyUsage[]>([]); const [collections, setCollections] = useState<VocabularyCollection[]>([]); const [usageDialogOpen, setUsageDialogOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [usageData, drillData] = await Promise.all([vocabularyPracticeApi.list(), vocabularyDrillApi.userData()]); setUsages(usageData.usages); setCollections(drillData.collections); } catch { setError(copy.loadFailed); } finally { setLoading(false); } }, [copy.loadFailed]);
  useEffect(() => { if (status === "authenticated" && user?.status === 1) { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); } }, [load, status, user?.status, user?.userId]);

  async function remove(usageId: string) {
    setError(""); try { await vocabularyPracticeApi.deleteUsage(usageId); setUsages((items) => items.filter((item) => item.usageId !== usageId)); toast.success(copy.removed); } catch { setError(copy.saveFailed); }
  }
  async function removeCollectionItem(collectionId: string, sourceWordId: number) { setError(""); try { await vocabularyDrillApi.deleteItem(collectionId, sourceWordId); setCollections(current => current.map(collection => collection.collectionId === collectionId ? { ...collection, items: collection.items.filter(item => Number(item.sourceWordId) !== sourceWordId) } : collection)); toast.success(copy.removed); } catch { setError(copy.saveFailed); } }

  if (status === "uninitialized") return <Box sx={{ minHeight: "70vh", display: "grid", placeItems: "center" }}><CircularProgress /></Box>;
  if (!isAuthenticated || user?.status !== 1) return <div className="page-below-navbar flex flex-col"><Box component="main" sx={{ flex: 1, display: "grid", placeItems: "center", px: 2 }}><Alert severity="info" action={<Button component={Link} href={user?.status === 0 ? "/verify-email" : "/login"}>{copy.signIn}</Button>}>{isAuthenticated ? copy.verify : copy.login}</Alert></Box><Footer /></div>;

  return <div className="page-below-navbar flex flex-col"><Box component="main" sx={{ flex: 1, px: { xs: 2, sm: 4 }, py: 5 }}><Box sx={{ width: "100%", maxWidth: 980, mx: "auto" }}><Typography component="h1" variant="h4" sx={{ mb: 1, fontWeight: 700 }}>{copy.title}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{copy.description}</Typography>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "240px minmax(0, 1fr)" }, gap: 2.5, alignItems: "start" }}>
      <Card variant="outlined" sx={{ borderRadius: 3, overflow: "hidden" }}><CardActionArea sx={{ p: 2, display: "flex", justifyContent: "flex-start", gap: 1.5, bgcolor: "action.selected" }}><Box sx={{ width: 38, height: 38, borderRadius: 2, display: "grid", placeItems: "center", color: "primary.main", bgcolor: "action.hover" }}><StorageRoundedIcon /></Box><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 700 }}>{copy.vocabulary}</Typography><Typography variant="caption" color="text.secondary">{copy.vocabularyHint}</Typography></Box><ChevronRightRoundedIcon color="action" /></CardActionArea></Card>
      <Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent sx={{ p: { xs: 2, sm: 3 } }}><Stack spacing={2}><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", gap: 1 }}><Box><Typography variant="h6" sx={{ fontWeight: 700 }}>{copy.vocabulary}</Typography><Typography variant="body2" color="text.secondary">{copy.vocabularyHint}</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => setUsageDialogOpen(true)}>{copy.add}</Button></Stack><Divider />
        {loading ? <Box sx={{ display: "grid", placeItems: "center", py: 5 }}><CircularProgress /></Box> : collections.length === 0 ? <Alert severity="info">{copy.empty}</Alert> : collections.map(collection => <CollectionBlock key={collection.collectionId} collection={collection} usages={usages.filter(item => item.collectionId === collection.collectionId)} copy={copy} locale={locale} onDeleteItem={removeCollectionItem} onDeleteUsage={remove} />)}
      </Stack></CardContent></Card>
      <VocabularyUsageDialog open={usageDialogOpen} locale={locale} collections={collections} onClose={() => setUsageDialogOpen(false)} onCollectionCreated={collection => setCollections(current => [...current, { ...collection, items: [] }])} onSaved={saved => { setUsages(current => [...current, saved].sort((a, b) => a.word.localeCompare(b.word) || a.prompt.localeCompare(b.prompt))); toast.success(copy.saved); }} />
    </Box>
  </Box></Box><Footer /></div>;
}

function CollectionBlock({ collection, usages, copy, locale, onDeleteItem, onDeleteUsage }: { collection: VocabularyCollection; usages: VocabularyUsage[]; copy: Record<keyof typeof words.en, string>; locale: "en" | "zh"; onDeleteItem: (collectionId: string, sourceWordId: number) => Promise<void>; onDeleteUsage: (usageId: string) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [page, setPage] = useState(0); const pageSize = 8;
  const normalized = query.trim().toLocaleLowerCase();
  const entries = [
    ...collection.items.map(item => ({ kind: "drill" as const, key: `drill:${item.dataset}:${item.sourceWordId}`, word: item.word, searchable: `${item.word} ${item.meanings.map(meaning => meaning.text).join(" ")}`, item })),
    ...usages.map(usage => ({ kind: "sentence" as const, key: `sentence:${usage.usageId}`, word: usage.word, searchable: `${usage.word} ${usage.prompt}`, usage })),
  ].filter(entry => !normalized || entry.searchable.toLocaleLowerCase().includes(normalized));
  const pageCount = Math.max(1, Math.ceil(entries.length / pageSize)); const safePage = Math.min(page, pageCount - 1); const visible = entries.slice(safePage * pageSize, (safePage + 1) * pageSize);
  return <Card variant="outlined" sx={{ borderRadius: 2.5, bgcolor: "action.hover" }}><CardContent><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", alignItems: { xs: "flex-start", sm: "center" }, gap: 1, mb: 1 }}><Typography variant="h6" sx={{ fontWeight: 700 }}>★ {collection.name}</Typography><Stack direction="row" spacing={1}><Button component={Link} href="/tools/english-learner/vocabulary-practice" size="small">{copy.vocabularyPractice}</Button><Button component={Link} href="/tools/english-learner/sentence-practice" size="small" startIcon={<MenuBookRoundedIcon />}>{copy.sentencePractice}</Button></Stack></Stack>
    <Typography variant="caption" color="text.secondary" component="p" sx={{ mb: 1.5 }}>{locale === "zh" ? "这个收藏夹由词汇练习和造句练习共用；两种练习各自保留进度和记录。" : "This collection is shared by vocabulary and sentence practice; each keeps its own progress and history."}{collection.orderGeneratedAt && <><br />{locale === "zh" ? "词汇练习本轮排序时间：" : "Vocabulary order generated: "}{reviewDate(collection.orderGeneratedAt, locale)}</>}</Typography>
    <TextField fullWidth size="small" placeholder={locale === "zh" ? "查找单词或释义" : "Find a word or meaning"} value={query} onChange={event => { setQuery(event.target.value); setPage(0); }} slotProps={{ input: { startAdornment: <SearchRoundedIcon color="action" sx={{ mr: 1 }} /> } }} sx={{ mb: 1.5 }} />{visible.length ? <Stack spacing={1}>{visible.map((entry, index) => <Box key={entry.key} sx={{ p: 1.5, border: 1, borderColor: "divider", borderRadius: 2, bgcolor: "background.paper" }}>
      <Stack direction="row" spacing={1} sx={{ alignItems: "flex-start" }}><Typography color="text.secondary" sx={{ fontSize: 13, pt: .4 }}>{safePage * pageSize + index + 1}.</Typography><Box sx={{ flex: 1, minWidth: 0 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap" }}><Typography sx={{ fontWeight: 700, overflowWrap: "anywhere" }}>{entry.word}</Typography><Chip size="small" variant="outlined" color={entry.kind === "drill" ? "primary" : "secondary"} label={entry.kind === "drill" ? copy.drillWords : copy.sentenceUsages} /></Stack>{entry.kind === "drill" ? <>{entry.item.phonetic && <Typography variant="caption" color="text.secondary">{entry.item.phonetic}</Typography>}<Typography variant="body2" sx={{ overflowWrap: "anywhere" }}>{entry.item.meanings.map(meaning => `${meaning.partOfSpeech}. ${meaning.text}`).join(" / ")}</Typography></> : <><Typography variant="body2">{entry.usage.prompt}</Typography><Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: "wrap", rowGap: 1 }}><Chip size="small" color="success" variant="outlined" label={`${copy.correct}: ${entry.usage.correct}`} /><Chip size="small" color="error" variant="outlined" label={`${copy.wrong}: ${entry.usage.wrong}`} /><Chip size="small" label={`${copy.recent}: ${entry.usage.last8CorrectRate}`} /><Chip size="small" label={entry.usage.lastLearnTime ? new Date(entry.usage.lastLearnTime).toLocaleString() : copy.never} /></Stack></>}</Box><Tooltip title={copy.delete}><IconButton size="small" color="error" onClick={() => entry.kind === "drill" ? void onDeleteItem(collection.collectionId, Number(entry.item.sourceWordId)) : void onDeleteUsage(entry.usage.usageId)}><DeleteOutlineRoundedIcon fontSize="small" /></IconButton></Tooltip></Stack>
      {entry.kind === "drill" ? <CollectionReviewDetails item={entry.item} locale={locale} /> : entry.usage.attempts.length > 0 && <Box sx={{ mt: 2 }}><Divider sx={{ mb: 1.5 }} /><Typography variant="subtitle2" sx={{ mb: 1 }}>{copy.history}</Typography><Stack spacing={1}>{entry.usage.attempts.map(attempt => <Box key={attempt.attemptId} sx={{ borderLeft: 3, borderColor: attempt.isCorrect ? "success.main" : "error.main", pl: 1.5, py: .5 }}><Typography variant="body2" sx={{ fontWeight: 600 }}>{attempt.isCorrect ? "✓" : "✗"} {attempt.answer}</Typography><Typography variant="caption" color="text.secondary">{new Date(attempt.createdAt).toLocaleString()} · {copy.example}: {attempt.exampleSentence}</Typography><Typography variant="body2"><strong>{copy.feedback}:</strong> {attempt.feedback}</Typography>{attempt.correctedSentence && <Typography variant="body2"><strong>{copy.corrected}:</strong> {attempt.correctedSentence}</Typography>}</Box>)}</Stack></Box>}
    </Box>)}</Stack> : <Typography color="text.secondary" sx={{ py: 2, textAlign: "center" }}>{normalized ? (locale === "zh" ? "没有找到匹配词语" : "No matching words") : copy.empty}</Typography>}<Stack direction="row" spacing={1} sx={{ justifyContent: "center", alignItems: "center", mt: 1.5 }}><IconButton size="small" disabled={safePage === 0} onClick={() => setPage(value => Math.max(0, value - 1))}><ChevronLeftRoundedIcon /></IconButton><Typography variant="caption">{safePage + 1} / {pageCount}</Typography><IconButton size="small" disabled={safePage >= pageCount - 1} onClick={() => setPage(value => Math.min(pageCount - 1, value + 1))}><ChevronRightRoundedIcon /></IconButton></Stack></CardContent></Card>;
}
